stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseNode@2  # This task sets up Node.js
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: |
        npm install
        npm run build
      displayName: 'Build the project'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'dist'  # Replace 'dist' with the path where your build output is stored
        artifact: 'drop'
      displayName: 'Publish Build Artifacts'
